// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/rotemtam/ent-blog-example/ent/runtime.go

const (
	Version = "v0.11.9-0.20230225191017-9020d2b961e7"           // Version of ent codegen.
	Sum     = "h1:GLXP1LYvkZFegM7pnDbJ5kyjlLAFeG1wBTxcK6s2y8M=" // Sum of ent codegen.
)
