// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/rotemtam/ent-blog-example/ent/runtime.go

const (
	Version = "v0.11.9-0.20230219143902-44327541440b"           // Version of ent codegen.
	Sum     = "h1:NVyFbH1Gt76nQ+M4ZnsI8R94VzuA2hskUybIcyWBJgQ=" // Sum of ent codegen.
)
